@RoomService_HostAddress = https://app-sos100-roomservice.azurewebsites.net

###
GET {{RoomService_HostAddress}}/api/rooms
Accept: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

###
POST {{RoomService_HostAddress}}/api/rooms
Content-Type: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

{
  "name": "London",
  "capacity": 4
}

###
POST {{RoomService_HostAddress}}/api/rooms
Content-Type: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

{
  "name": "Rom",
  "capacity": 6
}

###
POST {{RoomService_HostAddress}}/api/rooms
Content-Type: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

{
  "name": "Paris",
  "capacity": 8
}

###
POST {{RoomService_HostAddress}}/api/roombookings
Content-Type: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

{
  "roomId": 1,
  "bookedBy": "TestUser1",
  "startTime": "2026-03-15T10:00:00",
  "endTime": "2026-03-15T12:00:00"
}

###
GET {{RoomService_HostAddress}}/api/roombookings
Accept: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

###
DELETE {{RoomService_HostAddress}}/api/roombookings/1
X-API-KEY: ruqia-rooms-secret-key-2024

###
PUT {{RoomService_HostAddress}}/api/roombookings/1
Content-Type: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

{
  "id": 1,
  "roomId": 1,
  "bookedBy": "TestUser2",
  "startTime": "2026-03-15T13:00:00",
  "endTime": "2026-03-15T15:00:00"
}

###
GET {{RoomService_HostAddress}}/api/rooms/available?startTime=2026-03-15T09:00:00&endTime=2026-03-15T11:00:00
Accept: application/json
X-API-KEY: ruqia-rooms-secret-key-2024

