@RoomService_HostAddress = http://localhost:5091

###
GET {{RoomService_HostAddress}}/api/rooms
Accept: application/json

###
POST {{RoomService_HostAddress}}/api/rooms
Content-Type: application/json

{
  "name": "London",
  "capacity": 4
}
